package GUI;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import model.database.Controller;
import model.database.I_Bapers;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;


/**
 *
 * @author Manpreet
 */
public class AddTask extends javax.swing.JPanel {

    private I_Bapers bapers;
    private GUI f;
    private JPanel lastPanel;

    /**
     * Creates new form AddTask
     */
    public AddTask(int width, int height, int job_ID, I_Bapers bapers, GUI f) {
        initComponents (width, height, job_ID, bapers, f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(int width, int height, int job_ID, I_Bapers bapers, GUI f ) {

        this.f = f;
        this.lastPanel = f.getCurrentPanel();
        f.setCurrentPanel(this);
        this.bapers = bapers;
        back_button = new javax.swing.JButton();
        sign_out_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        task_list_input = new javax.swing.JComboBox<>();
        technician_list_input = new javax.swing.JComboBox<>();
        save_task_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(157, 195, 230));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));

        back_button.setBackground(new java.awt.Color(1, 23, 71));
        back_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back_button.setForeground(new java.awt.Color(157, 195, 230));
        back_button.setText("Back");
        back_button.setBorderPainted(false);
        back_button.setFocusPainted(false);
        back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                back_buttonMouseClicked(evt);
            }
        });

        sign_out_button.setBackground(new java.awt.Color(1, 23, 71));
        sign_out_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sign_out_button.setForeground(new java.awt.Color(157, 195, 230));
        sign_out_button.setText("Sign Out");
        sign_out_button.setBorderPainted(false);
        sign_out_button.setFocusPainted(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 23, 71));
        jLabel1.setText("Add Task");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 23, 71));
        jLabel2.setText("Task");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 23, 71));
        jLabel3.setText("Technician");

        task_list_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        task_list_input.setModel(new javax.swing.DefaultComboBoxModel<>(bapers.existingTasks()));
        task_list_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_list_input(evt, technician_list_input);
            }
        });

        technician_list_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        technician_list_input.setModel(new javax.swing.DefaultComboBoxModel<>(bapers.retrieveTechnicians(String.valueOf(task_list_input.getSelectedItem()))));

        save_task_button.setBackground(new java.awt.Color(1, 23, 71));
        save_task_button.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        save_task_button.setForeground(new java.awt.Color(157, 195, 230));
        save_task_button.setText("Save Task");
        save_task_button.setBorderPainted(false);
        save_task_button.setFocusPainted(false);
        save_task_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                save_task_buttonMouseClicked(evt, job_ID);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 23, 71));
        jLabel4.setText("Bapers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(back_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sign_out_button)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(task_list_input, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(technician_list_input, 0, 395, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(save_task_button, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel4)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_button)
                    .addComponent(sign_out_button))
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(task_list_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(technician_list_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(save_task_button)
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //save the task details in the database
    private void save_task_buttonMouseClicked(MouseEvent evt, int job_ID){
        if(!(task_list_input.getSelectedItem() == "Select Task") && !(technician_list_input.getSelectedItem() == "Select Technician")){
            bapers.createTask(String.valueOf(task_list_input.getSelectedItem()), job_ID, String.valueOf(technician_list_input.getSelectedItem()), "Pending");
            task_list_input.setSelectedItem("Select Task");
            technician_list_input.setSelectedItem("Select Technician");
        }
        else{
            JOptionPane.showMessageDialog(
                    this,
                    "Please fill out the fields.",
                    "BAPERS", JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void task_list_input(ActionEvent evt, JComboBox technician_list_input){
        technician_list_input.setModel(new javax.swing.DefaultComboBoxModel<>(bapers.retrieveTechnicians(String.valueOf(task_list_input.getSelectedItem()))));
    }

    //switch to previous panel
    private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {
        f.setLastPanel(lastPanel);
        f.getLastPanel().setVisible(true);
        f.remove(f.getCurrentPanel());
        f.setCurrentPanel(lastPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton save_task_button;
    private javax.swing.JButton sign_out_button;
    private javax.swing.JComboBox<String> task_list_input;
    private javax.swing.JComboBox<String> technician_list_input;
    // End of variables declaration//GEN-END:variables
}
