package GUI;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import model.database.Controller;
import model.database.I_Bapers;
import javax.swing.*;
import java.awt.event.MouseEvent;

/**
 *
 * @author Manpreet
 */
public class CreateJob extends JPanel {

    private I_Bapers bapers;
    private GUI f;
    private JPanel lastPanel;
    int id;

    /**
     * Creates new form CreateJob
     */
    public CreateJob(int width, int height, int customer_acc_no, I_Bapers bapers, GUI f) {
        initComponents(width, height, customer_acc_no, bapers, f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(int width, int height, int customer_acc_no, I_Bapers bapers, GUI f) {

        this.f = f;
        this.lastPanel = f.getCurrentPanel();
        f.setCurrentPanel(this);
        this.bapers = bapers;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        special_instructions_input = new javax.swing.JTextField();
        completion_deadline_input = new javax.swing.JTextField();
        description_input = new javax.swing.JTextField();
        add_task_button = new javax.swing.JButton();
        save_job_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        job_id_input = new javax.swing.JTextField();
        sign_out_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        priority_list_input = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(157, 195, 230));
        setMaximumSize(new java.awt.Dimension(width, height));
        setMinimumSize(new java.awt.Dimension(width, height));
        setPreferredSize(new java.awt.Dimension(width, height));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 23, 71));
        jLabel1.setText("Create Job");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 23, 71));
        jLabel2.setText("Priority");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 23, 71));
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 23, 71));
        jLabel4.setText("Completion Time (hrs) ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 23, 71));
        jLabel5.setText("Special Instructions ");

        special_instructions_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        special_instructions_input.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        completion_deadline_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        completion_deadline_input.setText("Optional (for custom priority only)");
        completion_deadline_input.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        completion_deadline_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                completion_deadline_inputFocusGained(evt);
            }
        });

        description_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        description_input.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        add_task_button.setBackground(new java.awt.Color(1, 23, 71));
        add_task_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add_task_button.setForeground(new java.awt.Color(157, 195, 230));
        add_task_button.setText("Add Task");
        add_task_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_task_button.setBorderPainted(false);
        add_task_button.setFocusPainted(false);
        add_task_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_task_buttonMouseClicked(evt, id);
            }
        });

        save_job_button.setBackground(new java.awt.Color(1, 23, 71));
        save_job_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        save_job_button.setForeground(new java.awt.Color(157, 195, 230));
        save_job_button.setText("Save Job");
        save_job_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_job_button.setBorderPainted(false);
        save_job_button.setFocusPainted(false);
        save_job_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_job_buttonMouseClicked(evt, customer_acc_no);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 23, 71));
        jLabel6.setText("Job ID");

        job_id_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        job_id_input.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sign_out_button.setBackground(new java.awt.Color(1, 23, 71));
        sign_out_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sign_out_button.setForeground(new java.awt.Color(157, 195, 230));
        sign_out_button.setText("Sign Out");
        sign_out_button.setBorderPainted(false);
        sign_out_button.setFocusPainted(false);
        sign_out_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_out_buttonMouseClicked(evt);
            }
        });

        back_button.setBackground(new java.awt.Color(1, 23, 71));
        back_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back_button.setForeground(new java.awt.Color(157, 195, 230));
        back_button.setText("Back");
        back_button.setBorderPainted(false);
        back_button.setFocusPainted(false);
        back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_buttonMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 23, 71));
        jLabel7.setText("Bapers");

        priority_list_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priority_list_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Priority Level", "Normal", "Urgent", "Custom" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(309, 309, 309))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(back_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sign_out_button)
                                .addGap(19, 19, 19))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel6))
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(description_input)
                                                        .addComponent(special_instructions_input)
                                                        .addComponent(completion_deadline_input, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                                        .addComponent(job_id_input)
                                                        .addComponent(priority_list_input, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(add_task_button, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addComponent(save_job_button, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(379, 379, 379)
                                                .addComponent(jLabel7)))
                                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(sign_out_button)
                                                        .addComponent(back_button))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(job_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(priority_list_input, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(description_input, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(completion_deadline_input, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(special_instructions_input, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(add_task_button)
                                                        .addComponent(save_job_button))
                                                .addGap(55, 55, 55))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_task_buttonMouseClicked(MouseEvent evt, int job_ID) {
        if (job_ID != 0){
            f.addTask(job_ID);
            setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(
                    this,
                    "Warning no job has been created!",
                    "BAPERS", JOptionPane.ERROR_MESSAGE
            );
        }

    }

    private void save_job_buttonMouseClicked(MouseEvent evt, int customer_acc_no) {//GEN-FIRST:event_save_job_buttonMouseClicked
        if (!job_id_input.getText().isEmpty() && !(priority_list_input.getSelectedItem() == "Select Priority Level") && !description_input.getText().isEmpty() && !special_instructions_input.getText().isEmpty()) {
            id = Integer.parseInt(job_id_input.getText());
            if (priority_list_input.getSelectedItem() == "Custom"){
                bapers.createJob(Integer.parseInt(job_id_input.getText()), description_input.getText(), String.valueOf(priority_list_input.getSelectedItem()), "Pending", Integer.parseInt(completion_deadline_input.getText()), special_instructions_input.getText(), customer_acc_no);
            }
            else {
                bapers.createJob(Integer.parseInt(job_id_input.getText()), description_input.getText(), String.valueOf(priority_list_input.getSelectedItem()), "Pending", 0, special_instructions_input.getText(), customer_acc_no);
            }
            job_id_input.setText("");
            description_input.setText("");
            priority_list_input.setSelectedItem("Select Priority Level");
            completion_deadline_input.setText("Optional (for custom priority only)");
            special_instructions_input.setText("");
        }
        else{
            JOptionPane.showMessageDialog(
                    this,
                    "Please fill out the required fields.",
                    "BAPERS", JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_save_job_buttonMouseClicked

    private void completion_deadline_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_completion_deadline_inputFocusGained
        completion_deadline_input.setText("");
    }//GEN-LAST:event_completion_deadline_inputFocusGained

    private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseClicked
        f.setLastPanel(lastPanel);
        f.getLastPanel().setVisible(true);
        f.remove(f.getCurrentPanel());
        f.setCurrentPanel(lastPanel);
    }//GEN-LAST:event_back_buttonMouseClicked

    private void sign_out_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_out_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sign_out_buttonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_task_button;
    private javax.swing.JButton back_button;
    private javax.swing.JTextField completion_deadline_input;
    private javax.swing.JTextField description_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField job_id_input;
    private javax.swing.JComboBox<String> priority_list_input;
    private javax.swing.JButton save_job_button;
    private javax.swing.JButton sign_out_button;
    private javax.swing.JTextField special_instructions_input;
    // End of variables declaration//GEN-END:variables
}
