package GUI;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manpreet
 */
public class ExistingTaskList extends javax.swing.JPanel {

    /**
     * Creates new form ExistingTaskList
     */
    public ExistingTaskList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        task_table_input = new javax.swing.JTable();
        add_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        remove_button = new javax.swing.JButton();
        refresh_button = new javax.swing.JButton();
        filter = new javax.swing.JComboBox<>();
        back_button = new javax.swing.JButton();
        save_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(157, 195, 230));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 23, 71));
        jLabel1.setText("Task List");

        task_table_input.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        task_table_input.setForeground(new java.awt.Color(1, 23, 71));
        task_table_input.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Task ID", "Description", "Location", "Price(£)", "Duration(min)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        task_table_input.setGridColor(new java.awt.Color(1, 23, 71));
        task_table_input.setSelectionBackground(new java.awt.Color(230, 238, 255));
        task_table_input.setSelectionForeground(new java.awt.Color(1, 23, 71));
        task_table_input.setShowGrid(true);
        task_table_input.getTableHeader().setResizingAllowed(false);
        task_table_input.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(task_table_input);

        add_button.setBackground(new java.awt.Color(1, 23, 71));
        add_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_button.setForeground(new java.awt.Color(157, 195, 230));
        add_button.setText("Add");
        add_button.setBorderPainted(false);
        add_button.setFocusPainted(false);
        add_button.setMaximumSize(new java.awt.Dimension(85, 25));
        add_button.setMinimumSize(new java.awt.Dimension(85, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 23, 71));
        jLabel2.setText("Bapers");

        remove_button.setBackground(new java.awt.Color(1, 23, 71));
        remove_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        remove_button.setForeground(new java.awt.Color(157, 195, 230));
        remove_button.setText("Remove");
        remove_button.setBorderPainted(false);
        remove_button.setFocusPainted(false);
        remove_button.setMaximumSize(new java.awt.Dimension(85, 25));
        remove_button.setMinimumSize(new java.awt.Dimension(85, 25));

        refresh_button.setBackground(new java.awt.Color(1, 23, 71));
        refresh_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refresh_button.setForeground(new java.awt.Color(157, 195, 230));
        refresh_button.setText("Refresh");
        refresh_button.setBorderPainted(false);
        refresh_button.setFocusPainted(false);

        filter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        filter.setForeground(new java.awt.Color(1, 23, 71));
        filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));
        filter.setMinimumSize(new java.awt.Dimension(108, 25));
        filter.setPreferredSize(new java.awt.Dimension(108, 25));

        back_button.setBackground(new java.awt.Color(1, 23, 71));
        back_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back_button.setForeground(new java.awt.Color(157, 195, 230));
        back_button.setText("Back");
        back_button.setBorderPainted(false);
        back_button.setFocusPainted(false);

        save_button.setBackground(new java.awt.Color(1, 23, 71));
        save_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save_button.setForeground(new java.awt.Color(157, 195, 230));
        save_button.setText("Save");
        save_button.setBorderPainted(false);
        save_button.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(save_button)
                .addGap(18, 18, 18)
                .addComponent(back_button)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(374, 374, 374))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remove_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refresh_button)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh_button))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_button)
                    .addComponent(back_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton back_button;
    private javax.swing.JComboBox<String> filter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh_button;
    private javax.swing.JButton remove_button;
    private javax.swing.JButton save_button;
    private javax.swing.JTable task_table_input;
    // End of variables declaration//GEN-END:variables
}
