package GUI;

import model.database.I_Bapers;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Mushfikur
 */
public class LoginPanel extends javax.swing.JPanel {

    private int width;
    private int height;
    private I_Bapers bapers;
    private GUI f;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(int width, int height, GUI f, I_Bapers bapers) {
        this.f = f;
        this.width = width;
        this.height = height;
        this.bapers = bapers;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        signInButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        signInLabel = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        idSpinner = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(157, 195, 230));
        setForeground(new java.awt.Color(1, 23, 71));

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idLabel.setForeground(new java.awt.Color(1, 23, 71));
        idLabel.setText("ID:");

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(1, 23, 71));
        passwordLabel.setText("Password:");

        signInButton.setBackground(new java.awt.Color(1, 23, 71));
        signInButton.setForeground(new java.awt.Color(157, 195, 230));
        signInButton.setText("Sign In");
        signInButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                signInButtonActionListener(e);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(1, 23, 71));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("BAPERS");

        signInLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(1, 23, 71));
        signInLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signInLabel.setText("Sign in");

        subtitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subtitle.setForeground(new java.awt.Color(1, 23, 71));
        subtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitle.setText("Photographic Labratory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(114, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(525, 525, 525))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(subtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(idSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(signInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(passwordLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(passwordInput))
                                                .addComponent(signInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subtitle)
                                .addGap(18, 18, 18)
                                .addComponent(signInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(idSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177))
        );

    }// </editor-fold>

    private void signInButtonActionListener(ActionEvent evt) {
        boolean authenticated = bapers.authenticateUser((int) idSpinner.getValue(), new String(passwordInput.getPassword()));
        if (authenticated) {
            System.out.println("Authentication success for " + bapers.getCurrentUser().toString());
            f.home();
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(
                    this,
                    "We could not find a password matching to that ID!",
                    "BAPERS", JOptionPane.ERROR_MESSAGE
            );
        }
    }


    // Variables declaration - do not modify                     
    private javax.swing.JLabel idLabel;
    private javax.swing.JSpinner idSpinner;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel title;
    // End of variables declaration                   
}
