package model;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * A class of useful methods that will be used throughout the system.
 */
public class Utils {

    /**
     * Returns the key that would be generated by AUTO_INCREMENT.
     * @param st The statement that will be executed
     * @return The id that AUTO_INCREMENT would generate.
     * @throws SQLException Incase of an SQLException, the error is handled.
     */
    public static int getGeneratedKey(Statement st) throws SQLException {

        try (ResultSet rs = st.getGeneratedKeys()) {
            if (rs.next()) {
                int key = rs.getInt(1);
                rs.close();
                return key;
            }else{
                throw new SQLException("Error getting generated key.. no key was found");
            }
        }
    }
}
